In [1]:
import pandas as pd
a=pd.read_csv('/content/Zoo.csv')
print(a)
print(a.isnull())
a=a.fillna(0)

      hair  feathers   eggs   milk  airborne  aquatic  predator  toothed  \
0     True     False  False   True     False    False      True     True   
1     True     False  False   True     False    False     False     True   
2    False     False   True  False     False     True      True     True   
3     True     False  False   True     False    False      True     True   
4     True     False  False   True     False    False      True     True   
..     ...       ...    ...    ...       ...      ...       ...      ...   
96    True     False  False   True     False    False     False     True   
97    True     False   True  False      True    False     False    False   
98    True     False  False   True     False    False      True     True   
99   False     False   True  False     False    False     False    False   
100  False      True   True  False      True    False     False    False   

     backbone  breathes  venomous   fins  legs   tail  domestic  catsize  \
0        Tr

In [2]:
import pandas as pd
c={'True':1,'False':0}
a=a.replace(c)
print(a)

      hair  feathers   eggs   milk  airborne  aquatic  predator  toothed  \
0     True     False  False   True     False    False      True     True   
1     True     False  False   True     False    False     False     True   
2    False     False   True  False     False     True      True     True   
3     True     False  False   True     False    False      True     True   
4     True     False  False   True     False    False      True     True   
..     ...       ...    ...    ...       ...      ...       ...      ...   
96    True     False  False   True     False    False     False     True   
97    True     False   True  False      True    False     False    False   
98    True     False  False   True     False    False      True     True   
99   False     False   True  False     False    False     False    False   
100  False      True   True  False      True    False     False    False   

     backbone  breathes  venomous   fins  legs   tail  domestic  catsize  \
0        Tr

In [3]:
y=a["type"]
print(y)

0             mammal
1             mammal
2               fish
3             mammal
4             mammal
           ...      
96            mammal
97            insect
98            mammal
99     mollusc.et.al
100             bird
Name: type, Length: 101, dtype: object


In [4]:
x=a.drop("type", axis=1)
print(x)

      hair  feathers   eggs   milk  airborne  aquatic  predator  toothed  \
0     True     False  False   True     False    False      True     True   
1     True     False  False   True     False    False     False     True   
2    False     False   True  False     False     True      True     True   
3     True     False  False   True     False    False      True     True   
4     True     False  False   True     False    False      True     True   
..     ...       ...    ...    ...       ...      ...       ...      ...   
96    True     False  False   True     False    False     False     True   
97    True     False   True  False      True    False     False    False   
98    True     False  False   True     False    False      True     True   
99   False     False   True  False     False    False     False    False   
100  False      True   True  False      True    False     False    False   

     backbone  breathes  venomous   fins  legs   tail  domestic  catsize  
0        Tru

LOGISTRIC REGRESSION

In [5]:
#logistric regression
from sklearn.metrics import accuracy_score, confusion_matrix
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.29,random_state=42)
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
Accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", Accuracy)

Accuracy: 0.9333333333333333


SUPPORT VECTOR MECHINE(SVM)


In [7]:
#SVM
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.metrics import accuracy_score, mean_squared_error
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
model = SVC(kernel='linear')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f'Accuracy: {acc}')

Accuracy: 0.9523809523809523


PERCEPTRON LEARNING


In [19]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
clf = Perceptron()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.9523809523809523


In [24]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Calculate and print precision
precision = precision_score(y_test, y_pred, average='weighted',zero_division=0)
print("Precision:", precision)

# Calculate and print recall
recall = recall_score(y_test, y_pred, average='weighted')
print("Recall:", recall)

# Calculate and print F1-score
f1 = f1_score(y_test, y_pred, average='weighted')
print("F1-score:", f1)

Confusion Matrix : 
 [[ 0  0  0  0  2  0  0]
 [ 0  3  0  0  0  0  0]
 [ 0  0  2  0  0  0  0]
 [ 0  0  0  3  0  2  0]
 [ 0  0  1  0 14  0  0]
 [ 0  0  1  1  0  1  0]
 [ 0  0  1  0  0  0  0]]
Accuracy: 0.7419354838709677
Precision: 0.6991935483870968
Recall: 0.7419354838709677
F1-score: 0.7104702442891829


KNN


In [20]:
#kNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
k=10
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.7419354838709677



# ** WITH PCA**

In [33]:
#PCA
from sklearn.decomposition import PCA
pca=PCA(4)
x1=pca.fit_transform(x)
print(x1)

[[ 1.35102851 -1.05853312  0.31410259 -0.04744328]
 [ 1.30663411 -1.20834446 -0.28940524  0.11802382]
 [-3.13165517  0.25220045  0.92941871  0.08172374]
 [ 1.35102851 -1.05853312  0.31410259 -0.04744328]
 [ 1.27729583 -1.22574951  0.12623911 -0.44224081]
 [ 1.30663411 -1.20834446 -0.28940524  0.11802382]
 [ 1.32106857 -1.25764259 -0.42160278  0.2966596 ]
 [-3.08788243  0.22030736  0.38157681  0.82062416]
 [-3.13165517  0.25220045  0.92941871  0.08172374]
 [ 1.37362871 -0.77104359 -0.26454275  1.08655033]
 [ 1.27729583 -1.22574951  0.12623911 -0.44224081]
 [-0.85560368  0.96028666 -1.44048974  0.03712295]
 [-3.13165517  0.25220045  0.92941871  0.08172374]
 [-2.73070318  0.94005387  0.35718272  0.75552254]
 [ 1.04663381  1.39432518  1.20986317  0.18374685]
 [ 2.98225622  1.55844133  1.41892651 -0.01557046]
 [-0.89937642  0.99217974 -0.89264785 -0.70177747]
 [ 1.30663411 -1.20834446 -0.28940524  0.11802382]
 [-3.11048263 -0.06718217  0.96022216 -0.31336946]
 [-2.9060239  -1.07047047  0.48

LOGISTRIC REGRESSION  WITH PCA


In [34]:
#logistric regression
from sklearn.metrics import accuracy_score, confusion_matrix
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
x_train, x_test, y_train, y_test = train_test_split(x1,y,test_size=0.29,random_state=42)
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
Accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", Accuracy)

Accuracy: 0.8333333333333334


SUPPORT VECTOR MECHINE(SVM)  WITH PCA



In [29]:
#SVM
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.metrics import accuracy_score, mean_squared_error
X_train, X_test, y_train, y_test = train_test_split(x1,y, test_size=0.2, random_state=42)
model = SVC(kernel='linear')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f'Accuracy: {acc}')

Accuracy: 0.9047619047619048


PERCEPTRON LEARNING  WITH PCA





In [30]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(x1, y, test_size=0.2, random_state=42)
clf = Perceptron()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.7142857142857143


KNN WITH PCA

In [32]:
#kNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(x1, y, test_size=0.3, random_state=42)
k=10
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.6774193548387096
